const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand();tg.setHeaderColor?.("#0d1017");tg.setBackgroundColor?.("#0d1017")}
const rarity={common:{label:"COMMON",color:"#9aa4b2",rank:1,weight:55},rare:{label:"RARE",color:"#2f8cff",rank:2,weight:27},epic:{label:"EPIC",color:"#a855f7",rank:3,weight:12},legendary:{label:"LEGENDARY",color:"#ffb020",rank:4,weight:5},mythic:{label:"MYTHIC",color:"#ff4757",rank:5,weight:1}};
const catalog=[{name:"Мідна монета",icon:"🪙",r:"common",d:"Проста колекційна монета."},{name:"Дерев'яний щит",icon:"🛡️",r:"common",d:"Щит для перших пригод."},{name:"Малий еліксир",icon:"🧪",r:"common",d:"Відновлює сили героя."},{name:"Синій кристал",icon:"🔷",r:"rare",d:"Кристал із холодним сяйвом."},{name:"Срібний меч",icon:"⚔️",r:"rare",d:"Зброя шукача пригод."},{name:"Сувій знань",icon:"📜",r:"rare",d:"Містить давній секрет."},{name:"Магічний капелюх",icon:"🎩",r:"epic",d:"Зберігає дивні заклинання."},{name:"Фіолетова сфера",icon:"🔮",r:"epic",d:"Показує фрагменти майбутнього."},{name:"Королівська корона",icon:"👑",r:"legendary",d:"Символ великої слави."},{name:"Золоте перо",icon:"🪶",r:"legendary",d:"Перо небесного птаха."},{name:"Яйце дракона",icon:"🥚",r:"mythic",d:"Найрідкісніша знахідка."}];
let state=JSON.parse(localStorage.getItem("cg_v1")||'{"opened":[],"inventory":[]}'),pending=null,pendingId=null;const $=id=>document.getElementById(id);
function save(){localStorage.setItem("cg_v1",JSON.stringify(state))}function rollRarity(){let x=Math.random()*100;for(const [k,v] of Object.entries(rarity)){x-=v.weight;if(x<0)return k}return"common"}function makeReward(){const r=rollRarity(),pool=catalog.filter(x=>x.r===r);return{...pool[Math.floor(Math.random()*pool.length)],time:Date.now()}}
function renderBoxes(){$("grid").innerHTML="";for(let i=1;i<=100;i++){const opened=state.opened.includes(i),b=document.createElement("button");b.className="container "+(opened?"opened":"");b.disabled=opened;b.innerHTML=`<span class="num">#${String(i).padStart(3,"0")}</span><span class="emoji">${opened?"✅":"📦"}</span><span class="status">${opened?"Відкрито":"Натисни, щоб відкрити"}</span>`;b.onclick=()=>openBox(i);$("grid").appendChild(b)}}
function renderItems(){$("items").innerHTML="";$("empty").style.display=state.inventory.length?"none":"block";[...state.inventory].reverse().forEach(x=>{const c=document.createElement("article"),info=rarity[x.r];c.className="item";c.innerHTML=`<div class="icon">${x.icon}</div><h3>${x.name}</h3><p>${x.d}</p><span class="pill" style="background:${info.color}">${info.label}</span>`;$("items").appendChild(c)})}
function stats(){$("opened").textContent=state.opened.length;$("count").textContent=state.inventory.length;$("badge").textContent=state.inventory.length;if(!state.inventory.length){$("best").textContent="—";return}const best=state.inventory.reduce((a,b)=>rarity[a.r].rank>=rarity[b.r].rank?a:b);$("best").textContent=rarity[best.r].label;$("best").style.color=rarity[best.r].color}
function render(){renderBoxes();renderItems();stats()}function openBox(id){if(state.opened.includes(id))return;pendingId=id;pending=makeReward();$("modal").classList.add("show");$("loading").classList.remove("hidden");$("reward").classList.add("hidden");tg?.HapticFeedback?.impactOccurred("medium");setTimeout(()=>{const info=rarity[pending.r];$("loading").classList.add("hidden");$("reward").classList.remove("hidden");$("rewardIcon").textContent=pending.icon;$("rarity").textContent=info.label;$("rarity").style.background=info.color;$("rewardName").textContent=pending.name;$("desc").textContent=pending.d},1200)}
function close(){$("modal").classList.remove("show")}function collect(){if(!pending)return;state.opened.push(pendingId);state.inventory.push(pending);save();render();close();toast(`Отримано: ${pending.icon} ${pending.name}`);pending=null;pendingId=null}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>$("toast").classList.remove("show"),2000)}
const user=tg?.initDataUnsafe?.user;if(user)$("user").textContent=`👤 ${user.first_name||"Гравець"}`;document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));t.classList.add("active");$(t.dataset.panel).classList.add("active")});$("random").onclick=()=>{const a=Array.from({length:100},(_,i)=>i+1).filter(i=>!state.opened.includes(i));a.length?openBox(a[Math.floor(Math.random()*a.length)]):toast("Усі контейнери відкриті")};$("collect").onclick=collect;$("close").onclick=close;document.querySelector(".backdrop").onclick=close;$("reset").onclick=()=>{if(confirm("Скинути весь прогрес?")){state={opened:[],inventory:[]};save();render();toast("Прогрес скинуто")}};render();